# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://www.prairielearn.org/")
    self.driver.set_window_size(1440, 875)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.LINK_TEXT, "Sign in with Illinois").click()
    self.driver.find_element(By.ID, "userNameInput").send_keys("apirani2@illinois.edu")
    self.driver.find_element(By.ID, "passwordInput").send_keys("77aydaN77")
    self.driver.find_element(By.ID, "userNameInput").send_keys("apirani2@illinois.edu")
    self.driver.find_element(By.ID, "userNameInput").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "passwordInput").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "userNameInput").send_keys("apirani2@illinois.edu")
    self.driver.find_element(By.LINK_TEXT, "CS 225: Data Structures and Algorithms, Spring 2022").click()
    self.driver.find_element(By.LINK_TEXT, "MATH 257: Linear Algebra with Computational Applications, MATH 257 - Spring 2022").click()
    self.driver.find_element(By.LINK_TEXT, "CS 199225: Undergraduate Open Seminar - CS 225 Honors, SP 2022").click()
    self.driver.find_element(By.LINK_TEXT, "CS 233: Computer Architecture, Spring 2022").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-flourish").click()
  
